name: Scrape

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Run Scraper
        run: python woldometres_scraping.py
