name: Scrape

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest version compatible

      - name: Set up Python
        uses: actions/setup-python@v4 # Use the latest version compatible
        with:
          python-version: 3.8
      - name: Run Scraper
        run: |
          python -m pip install -r .github/workflows/requirements.txt 
          python woldometres_scraping.py
      - name : Git automatic push 
        run:
         git config --global user.name "DATaxelBase"
         git config --global user.email "axel.damatha@gmail.com"
         git add * 
         git commit -m "dataset update"
         git push
